server:
  port:8080
mpesa:
  daraja:
    consumer-key: mhxXybc5iozGrlwBkAiOGYSNXE7UcIAL
    consumer-secret: ykys7qAGxgVFEglS
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode: 603021
    confirmationURL: https://f142-197-156-190-181.ngrok.io/mobile-money/confirmation
    validationURL: https://f142-197-156-190-181.ngrok.io/mobile-money/validation
    responseType: Completed
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://f142-197-156-190-181.ngrok.io/mobile-money/b2c-transaction-result
    b2c-queue-timeout-url: https://f142-197-156-190-181.ngrok.io/mobile-money/b2c-queue-timeout
    b2c-initiator-name: apiop37
    b2c-initiator-password: Safaricom3021#
